### ISSUE TITLE
unable to export to external Prometheus server

### ISSUE THREAD

**Issue by ravieze** [jirwin/burrow_exporter#20]
Hi,

I have a working grafana with prometheus server (on a node). ON a diffarent node I am runnibng burow and burrow_exporter (as 2 docker services). For burrow_exporter i have the below configuration. when i see burrow_logs i dont see any errors (docker logs -f <docker pid>; I see Scraping burrow.. , and Finished scraping burrow....  ). But i dont see any entries into my prometheus server with substring "burrow" so clearly the scrapped data is not sent across.

if you can give me a way to push data from burrow_exporter to external promethus server over an arbitary IP, will be a great help. 

```
services:
  burrow:
    build: .
    environment:
        BURROW_ADDR: http://172.31.18.137:8000
        METRICS_ADDR: 172.31.18.137:9090
        INTERVAL: 5
        API_VERSION: 3
    volumes:
      - ../burrow-master/docker-config:/etc/burrow/
      - ${PWD}/tmp:/var/tmp/burrow

```
