### ISSUE TITLE
Burrow native Prometheus Metrics support

### ISSUE THREAD

**Issue by macropin** [jirwin/burrow_exporter#44]
Prometheus support was added to https://github.com/linkedin/Burrow/pull/628 in 2020.

Is this project still relevant? May I suggest that you update your documentation.

**Comment by adkafka** [comment]
For the next person to come along, if you are used to the official Burrow format of metrics and you want to translate metrics from this project into that format, this config should help:

```
        - job_name: 'burrow'
          metrics_path: '/metrics'
          scrape_interval: '10s'
          scheme: 'https'
          static_configs:
            - targets:
                - "HOSTNAME"
          metric_relabel_configs:
            # Rename kafka_burrow_partition_lag to burrow_kafka_consumer_partition_lag
            - source_labels: [__name__]
              regex: kafka_burrow_partition_lag
              target_label: __name__
              replacement: burrow_kafka_consumer_partition_lag
            # Rename group label to consumer_group
            - source_labels: [group]
              target_label: consumer_group
              replacement: $1
            # Drop the original group label
            - regex: group
              action: labeldrop
            # Rename kafka_burrow_partition_current_offset to burrow_kafka_consumer_current_offset
            - source_labels: [__name__]
              regex: kafka_burrow_partition_current_offset
              target_label: __name__
              replacement: burrow_kafka_consumer_current_offset
            # Rename kafka_burrow_status to burrow_kafka_consumer_status
            - source_labels: [__name__]
              regex: kafka_burrow_status
              target_label: __name__
              replacement: burrow_kafka_consumer_status
            # Rename kafka_burrow_topic_partition_offset to burrow_kafka_topic_partition_offset
            - source_labels: [__name__]
              regex: kafka_burrow_topic_partition_offset
              target_label: __name__
              replacement: burrow_kafka_topic_partition_offset
            # Rename kafka_burrow_total_lag to burrow_kafka_consumer_lag_total
            - source_labels: [__name__]
              regex: kafka_burrow_total_lag
              target_label: __name__
              replacement: burrow_kafka_consumer_lag_total
            # Drop kafka_burrow_partition_max_offset (no matching Burrow metric)
            - source_labels: [__name__]
              regex: kafka_burrow_partition_max_offset
              action: drop
```
